In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

data = pd.read_csv('Churn_Modelling.csv')

X = data.iloc[:,3:-1]
y = data.iloc[:,-1]
data

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [2]:
X

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1   
1             608     Spain  Female   41       1   83807.86              1   
2             502    France  Female   42       8  159660.80              3   
3             699    France  Female   39       1       0.00              2   
4             850     Spain  Female   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France    Male   39       5       0.00              2   
9996          516    France    Male   35      10   57369.61              1   
9997          709    France  Female   36       7       0.00              1   
9998          772   Germany    Male   42       3   75075.31              2   
9999          792    France  Female   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  
0             1               1        101348.88  
1             0               1        112542.58  
2             1               0        113931.57  
3             0               0         93826.63  
4             1               1         79084.10  
...         ...             ...              ...  
9995          1               0         96270.64  
9996          1               1        101699.77  
9997          0               1         42085.58  
9998          1               0         92888.52  
9999          1               0         38190.78  

[10000 rows x 10 columns]

In [3]:
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [4]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer([('encoder', OneHotEncoder(), [1, 2])], remainder='passthrough')
X = ct.fit_transform(X)


In [5]:
X

array([[1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [6]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [7]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [8]:
from keras.models import Sequential
ann = Sequential()


In [9]:
from keras.layers import Dense

ann.add(Dense(units = 6, activation='relu'))

In [10]:
ann.add(Dense(units = 1, activation = 'sigmoid'))

In [11]:
ann.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [12]:
history = ann.fit(X_train, y_train, epochs=100, batch_size=100)

Epoch 1/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 1s 787us/step - accuracy: 0.5957 - loss: 0.7123
Epoch 2/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 709us/step - accuracy: 0.7202 - loss: 0.5884
Epoch 3/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 645us/step - accuracy: 0.7785 - loss: 0.5314
Epoch 4/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 666us/step - accuracy: 0.7873 - loss: 0.5056
Epoch 5/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 673us/step - accuracy: 0.7903 - loss: 0.4759
Epoch 6/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 695us/step - accuracy: 0.7943 - loss: 0.4695
Epoch 7/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 708us/step - accuracy: 0.8048 - loss: 0.4461
Epoch 8/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 645us/step - accuracy: 0.8095 - loss: 0.4366
Epoch 9/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 683us/step - accuracy: 0.8070 - loss: 0.4313
Epoch 10/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 703us/step - accuracy: 0.8058 - loss: 0.4380
Epoch 11/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 727us/step - accuracy: 0.8187 - loss: 0.4230
Epoch 12/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0

In [13]:
ann.predict(X_test)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step  


array([[0.30842814],
       [0.3596654 ],
       [0.16284256],
       ...,
       [0.17076632],
       [0.22596668],
       [0.23302005]], dtype=float32)

In [14]:
encoder = ct.named_transformers_['encoder']
encoder.categories_

[array(['France', 'Germany', 'Spain'], dtype=object),
 array(['Female', 'Male'], dtype=object)]

In [15]:
ann.predict(scaler.transform([[0, 0, 1, 0, 1, 608, 41, 1, 83807, 1, 0, 1, 112542]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step


array([[0.17225726]], dtype=float32)

In [16]:
ann.predict(scaler.transform([[1, 0, 0, 600, 0, 1, 40, 3, 6000, 2, 1, 1, 50000]])) > 0.5

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step


array([[False]])

In [23]:
from sklearn.metrics import accuracy_score, confusion_matrix

y_pred = ann.predict(X_test)
y_pred = y_pred > 0.5

print(confusion_matrix(y_test, y_pred))

accuracy = accuracy_score(y_test, y_pred)
print('Accuracy:', accuracy)


63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 580us/step
[[1515   80]
 [ 193  212]]
Accuracy: 0.8635
